services:
  app:
    container_name: todo-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /var/www/html
    ports:
      - 8080:80

  db:
    container_name: todo-db
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: mariadb-data
        target: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root

  ubuntu:
    container_name: todo-ubuntu
    build:
      context: .
      dockerfile: docker/ubuntu/Dockerfile
    tty: true

volumes:
  mariadb-data:
